language: ruby
rvm:
- 2.1
before_script: npm install
install: bundle install
script: npm run prod
after_success: bundle exec s3_website push
branches:
  only:
  - stable
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: jlcamI//fH2Rc9yadX1wkPexVbHoKuVb6wnD9iHBEl3FSQEz11uCkFKUolxdmiCHPUyet2LUcYOSKl2FpEtteL3bwTDuwI7YcJwU16tzMmNVUgR2LiZTB8S6BHUAulosRhk47mXcrVPgWsgvmzxEMI1Ot7wZaZOQhtX/BDfmODo=
  - secure: cQxNTt3KClCZVgYsyKcwWGJ1qHIKSkKdpI3LlUjAVw4lY0X8hjX9StcyV9v3BHF651714T/Kb327+BXXKAMVcqUc4nIeFfg2UAAAd0kqEK0+GYmZq2POTPTOrJcHOsDKAYHzpm4Fh48ZiLccjSe3/1AU9zkm67DO2P5ZY68CDX0=
